import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 1. إعداد تجميع كود الـ TypeScript (main.ts -> main.js)
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

// 2. إعداد تجميع ملفات الـ SCSS (src/styles/index.scss -> styles.css)
const styleContext = await esbuild.context({
  entryPoints: ["src/styles/index.scss"],
  outfile: "styles.css",
  bundle: true,
  minify: prod,
  plugins: [sassPlugin()],
});

if (prod) {
  // بناء نسخ الإنتاج المجمعة
  await context.rebuild();
  await styleContext.rebuild();

  // تنظيف السياق وتحرير الموارد
  await context.dispose();
  await styleContext.dispose();

  console.log("BUILD SUCCESSFUL!"); // 👈 رسالة التنبيه عند نجاح البناء النهائى
  process.exit(0);
} else {
  // تفعيل وضع المراقبة اللحظية أثناء التطوير
  await context.watch();
  await styleContext.watch();
  console.log(
    "WATCH MODE STARTED: Watching for changes in JS/TS and SCSS files...",
  ); // 👈 تنبيه بدء وضع المراقبة
}
